package maven

import (
	"fmt"
	"testing"
)

func TestX(t *testing.T) {
	pom := CreateProject()
	pom.Parent = &Parent{
		Coordinates: Coordinates{
			GroupID:    "tech.f3s",
			ArtifactID: "parent",
			Version:    "999",
		},
	}
	pom.GroupID = "tech.f3s"
	pom.ArtifactID = "market-model"
	pom.Version = "1.0.0-SNAPSHOT"
	pom.Packaging = "pom"
	pom.Name = "f3s test project"
	pom.Description = "Super cool maven project generated by go!"
	pom.Url = "https://www.f3s.tech"
	pom.InceptionYear = "2022"
	pom.Dependencies = &Dependencies{
		Elements: []Dependency{
			{
				Coordinates: Coordinates{
					GroupID:    "tech.f3s",
					ArtifactID: "lib-a",
					Version:    "1.0",
				},
			},
		},
	}
	pom.DependencyManagement = &DependencyManagement{
		Dependencies: &Dependencies{
			Elements: []Dependency{
				{
					Coordinates: Coordinates{
						GroupID:    "tech.f3s",
						ArtifactID: "lib-a",
						Version:    "1.0",
					},
				},
			},
		},
	}

	properties := make(map[string]string)
	properties["p1"] = "value-1"
	properties["p2"] = "value-2"
	properties["p3"] = "value-3"

	pom.Properties = &Properties{
		Entries: properties,
	}
	pom.Modules = &Modules{
		Elements: []string{"a", "b", "c"},
	}

	if data, err := pom.MarshalIndent("", "  "); err != nil {
		t.Error(err)
	} else {
		fmt.Println(string(data))
	}
}
